# Generated by Django 5.0.3 on 2024-03-08 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='height',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='weight',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
