# Generated by Django 5.0.3 on 2024-03-09 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_remove_pokemon_height_remove_pokemon_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='abilities',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='stats',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
